spring:
  application:
    name: order-service
    
#server:#  port: 8201
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
#f.h.e
feign:  hystrix:    enabled: true

#m.e.w.e.s.i  

---
spring:
  profiles: order1
  
server:
  port: 8201
  
---
spring:
  profiles: order2
  
server:
  port: 8202

          